# Generated by Django 5.1.5 on 2025-01-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ad_account_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='app_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
