# Generated by Django 5.1.5 on 2025-01-23 06:12

import adminconsole.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0002_user_access_token_user_ad_account_id_user_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(null=True, upload_to='profile', validators=[adminconsole.validators.validate_image]),
        ),
    ]
