# Generated by Django 5.1.5 on 2025-01-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0003_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=100, unique=True)),
                ('ad_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('post_link', models.URLField(blank=True, max_length=500, null=True)),
                ('video_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(max_length=100, unique=True)),
                ('adset_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('objective', models.CharField(max_length=100)),
                ('bid_strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('landing_page_views', models.IntegerField(blank=True, null=True)),
                ('checkouts_initiated', models.IntegerField(blank=True, null=True)),
                ('add_to_carts', models.IntegerField(blank=True, null=True)),
                ('add_payment_info', models.IntegerField(blank=True, null=True)),
                ('cost_per_result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('video_views', models.IntegerField(blank=True, null=True)),
                ('hook_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hold_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='adminconsole.ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='adset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='adminconsole.adset'),
        ),
        migrations.AddField(
            model_name='adset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='adminconsole.campaign'),
        ),
    ]
