# Generated by Django 5.1.5 on 2025-01-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0004_ad_adset_campaign_admetrics_ad_adset_adset_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admetrics',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adset',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
