# Generated by Django 5.1.5 on 2025-01-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0005_ad_response_data_admetrics_response_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='amount_spent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admetrics',
            name='cost_per_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admetrics',
            name='cpc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admetrics',
            name='cpm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admetrics',
            name='ctr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admetrics',
            name='roas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adset',
            name='amount_spent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adset',
            name='daily_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_spent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='daily_budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
