# Generated by Django 5.1.5 on 2025-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0006_alter_ad_amount_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fbAdMetrics',
            fields=[
                ('ad_id', models.CharField(help_text='Unique identifier for the ad', max_length=255, primary_key=True, serialize=False)),
                ('period_start', models.DateField(blank=True, help_text='Start date for the reporting period', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End date for the reporting period', null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_objective', models.CharField(blank=True, max_length=100, null=True)),
                ('adset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('bid_strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('daily_budget', models.CharField(blank=True, max_length=255, null=True)),
                ('results', models.CharField(blank=True, help_text='Total conversion events (or other results as defined)', max_length=255, null=True)),
                ('cost_per_result', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_spent', models.CharField(blank=True, max_length=255, null=True)),
                ('return_on_ad_spend', models.CharField(blank=True, max_length=255, null=True)),
                ('hook_rate', models.CharField(blank=True, help_text='Custom metric: Hook Rate (if calculated)', max_length=255, null=True)),
                ('hold_rate', models.CharField(blank=True, help_text='Custom metric: Hold Rate (if calculated)', max_length=255, null=True)),
                ('cpm', models.CharField(blank=True, max_length=255, null=True)),
                ('link_ctr', models.CharField(blank=True, max_length=255, null=True)),
                ('link_cpc', models.CharField(blank=True, max_length=255, null=True)),
                ('link_clicks', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_page_views', models.CharField(blank=True, max_length=255, null=True)),
                ('checkouts_initiated', models.CharField(blank=True, max_length=255, null=True)),
                ('add_to_carts', models.CharField(blank=True, max_length=255, null=True)),
                ('add_payment_info', models.CharField(blank=True, max_length=255, null=True)),
                ('creative_link', models.URLField(blank=True, help_text='URL to the image or video creative', max_length=500, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
