# Generated by Django 5.1.5 on 2025-02-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0007_fbadmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbadmetrics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbadmetrics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
