# Generated by Django 5.1.5 on 2025-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminconsole', '0008_alter_fbadmetrics_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbadmetrics',
            name='period_end',
            field=models.CharField(blank=True, help_text='End date for the reporting period', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbadmetrics',
            name='period_start',
            field=models.CharField(blank=True, help_text='Start date for the reporting period', max_length=255, null=True),
        ),
    ]
